Isbn
officeluv/gtin_extras pull request #3
Opened 2018-09-28 03:00 UTC by tophersjones

isbn.rb file created, 
isbn tests created in gtin_extras_spec.rb

2018-09-28 17:57 UTC, andjosh commented
Addresses #1 

@tophersjones Do you think we should also add info about this new module to the README?

2018-09-28 18:29 UTC, tophersjones commented
Sure thing, just pushed another commit

2018-09-28 18:30 UTC, joshbeckman requested changes
Couple other notes

2018-09-28 18:30 UTC, joshbeckman commented on spec/gtin_extras_spec.rb
> +    it 'rejects bad 10 digit ISPN' do
I think this and the test titles below have a typo 😄

2018-09-28 18:30 UTC, joshbeckman commented on lib/gtin_extras/isbn.rb
> +    self.replace(self.tr('- ', ''))
This could be simplified to replace more than just hyphens (as in the other validators) to be:

```rb
str = to_s.gsub(/[\D]+/, '')
```

2018-09-28 18:58 UTC, tophersjones commented on spec/gtin_extras_spec.rb
> +    it 'rejects bad 10 digit ISPN' do
OH I finally see what you're talking about

2018-09-28 18:59 UTC, tophersjones commented on spec/gtin_extras_spec.rb
> +    it 'rejects bad 10 digit ISPN' do
We can validate the ESPN next

2018-10-01 15:56 UTC, joshbeckman approved these changes

2018-10-01 15:57 UTC, merged